---

ultraesb_patch_version:         "016"
custom_libs_zip:                "ots_lib_custom_jars.zip"

ultraesb_major_version: 2.6
ultraesb_minor_version: 1
java_home:              "/opt/jdk1.8.0_92"
custom_libs_zip:        "ots_lib_custom_jars.zip"
