
jenkins_connection_delay: 5
jenkins_connection_retries: 10
jenkins_home: /var/lib/jenkins
jenkins_hostname: "{{ansible_host}}"
jenkins_http_port: 9090
jenkins_url:  "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}"
jenkins_jar_location: /var/lib/jenkins/
jenkins_java_options: "-Djenkins.install.runSetupWizard=false"
jenkins_plugin_updates_expiration: 86400
jenkins_admin_username: admin
jenkins_admin_password: admin
key: jenkins-ci.org.key
url: http://pkg.jenkins-ci.org
deb: debian-stable
jenkins_url_prefix: " "
jenkins_apt_key: "{{ url }}/{{deb}}/{{ key }}"
jenkins_apt_key_id: D50582E6
jenkins_apt_repository: deb http://pkg.jenkins-ci.org/debian-stable binary/
cache_updated: true
dependencies:
  - 'git'
  - 'curl'
