---
 
- hosts: besb

  roles:
    - { role: common, app_user: "ultraesb" }
    - { role: linux-jdk, jdk_installer: "jdk-7u51-linux-x64", app_user: "ultraesb" }
    - { role: ultraesb, uesb_instances: "{{ besb_instances }}" } 

