---
 
- hosts: datasync_uesb
  roles:
    - { role: common, app_user: "ultraesb", app_user_home: "{{ uesb_app_user_home }}" }
    - { role: linux-jdk, jdk_installer: "jdk-7u51-linux-x64", app_user: "ultraesb" }
    - { role: ultraesb, uesb_instances: "{{ datasync_uesb_instances }}" }
  serial: 1
