---
 #This playbook provisions the r9-ist environment. The roles below lists the softwares provisioned. Also the r9-ist/hosts file details the environment.

- hosts:        hornetq

  roles:
    - { role: common, app_user: "hornetq" }
    - { role: linux-jdk, jdk_installer: "jdk-7u51-linux-x64", app_user: "hornetq" }
    - { role: hornetq, app_user: "hornetq" }
