---
tomcat_instances:
  - tc2
  - tc3

app:  "tomcat8"

tomcat_version:       "7.0.57"
jdk_installer:      "jdk-7u51-linux-x64"
java_home:            "/opt/jdk1.7.0_51"


#tomcat_version:       "8.0.43"
#jdk_installer:      "jdk-8u92-linux-x64"
#java_home:            "/opt/jdk1.8.0_92"